import "dotenv/config";
import axios from "axios";


const server = process.env.SERVER_URL || "";
console.log("server", server);

const createProducts = () => {
  const testData = [
    {
      id: "1",
      img: "t-shirt1.jpg",
      name: "Casual T-Shirt",
      text: "Fashion never stops. There is always the new project, the new opportunity. The important thing is to take your time and not get stressed. I just want to do what I do.",
      type: "T-Shirts",
      size: ["XL", "L", "M", "S"],
      color: ["black", "gray", "green"],
      gender: "male",
      price: 45,
    },
    {
      id: "2",
      img: "t-shirt2.jpg",
      name: "Casual T-Shrit",
      text: "Fashion never stops. There is always the new project, the new opportunity. The important thing is to take your time and not get stressed. I just want to do what I do.",
      type: "T-Shirts",
      size: ["M", "L", "XL"],
      color: ["black", "red", "brown"],
      gender: "male",
      price: 55,
    },
    {
      id: "3",
      img: "t-shirt3.jpg",
      name: "Casual T-Shrit",
      text: "Fashion never stops. There is always the new project, the new opportunity. The important thing is to take your time and not get stressed. I just want to do what I do.",
      type: "T-Shirts",
      size: ["L", "XL"],
      color: ["brown", "gray", "yellow"],
      gender: "female",
      price: 75,
    },
    {
      id: "4",
      img: "t-shirt4.jpg",
      name: "Casual T-Shrit",
      text: "Fashion never stops. There is always the new project, the new opportunity. The important thing is to take your time and not get stressed. I just want to do what I do.",
      type: "T-Shirts",
      size: ["M", "L", "XL"],
      color: ["gray", "orange", "blue"],
      gender: "female",
      price: 25,
    },
    {
      id: "5",
      img: "t-shirt5.jpg",
      name: "Casual T-Shrit",
      text: "Fashion never stops. There is always the new project, the new opportunity. The important thing is to take your time and not get stressed. I just want to do what I do.",
      type: "T-Shirts",
      size: ["M", "L", "XL"],
      color: ["black", "brown", "blue"],
      gender: "female",
      price: 15,
    },
    {
      id: "6",
      img: "t-shirt6.jpg",
      name: "Casual T-Shrit",
      text: "Fashion never stops. There is always the new project, the new opportunity. The important thing is to take your time and not get stressed. I just want to do what I do.",
      type: "T-Shirts",
      size: ["M", "L", "XL"],
      color: ["gray", "purple", "yellow"],
      gender: "female",
      price: 25,
    },
    {
      id: "7",
      img: "t-shirt7.jpg",
      name: "Casual T-Shrit",
      text: "Fashion never stops. There is always the new project, the new opportunity. The important thing is to take your time and not get stressed. I just want to do what I do.",
      type: "T-Shirts",
      size: ["M", "L", "XL"],
      color: ["black", "orange", "blue"],
      gender: "male",
      price: 25,
    },
    {
      id: "8",
      img: "t-shirt8.jpg",
      name: "Casual T-Shrit",
      text: "Fashion never stops. There is always the new project, the new opportunity. The important thing is to take your time and not get stressed. I just want to do what I do.",
      type: "T-Shirts",
      size: ["M", "XL"],
      color: ["gray", "red", "blue"],
      gender: "male",
      price: 35,
    },

    {
      id: "9",
      img: "hoodie1.jpg",
      name: "Casual Hoodie",
      text: "Fashion never stops. There is always the new project, the new opportunity. The important thing is to take your time and not get stressed. I just want to do what I do.",
      type: "Hoodies",
      size: ["S", "L", "XL"],
      color: ["blue", "red", "green"],
      gender: "female",
      price: 85,
    },
    {
      id: "10",
      img: "hoodie2.jpg",
      name: "Casual Hoodie",
      text: "Fashion never stops. There is always the new project, the new opportunity. The important thing is to take your time and not get stressed. I just want to do what I do.",
      type: "Hoodies",
      size: ["S", "L", "XL"],
      color: ["gray", "purple", "black"],
      gender: "female",
      price: 95,
    },
    {
      id: "11",
      img: "hoodie3.jpg",
      name: "Casual Hoodie",
      text: "Fashion never stops. There is always the new project, the new opportunity. The important thing is to take your time and not get stressed. I just want to do what I do.",
      type: "Hoodies",
      size: ["S", "M", "XL"],
      color: ["red", "blue", "black"],
      gender: "male",
      price: 95,
    },
    {
      id: "12",
      img: "hoodie4.jpg",
      name: "Casual Hoodie",
      text: "Fashion never stops. There is always the new project, the new opportunity. The important thing is to take your time and not get stressed. I just want to do what I do.",
      type: "Hoodies",
      size: ["S", "XL"],
      color: ["gray", "blue", "red"],
      gender: "male",
      price: 125,
    },
    {
      id: "13",
      img: "hoodie5.jpg",
      name: "Casual Hoodie",
      text: "Fashion never stops. There is always the new project, the new opportunity. The important thing is to take your time and not get stressed. I just want to do what I do.",
      type: "Hoodies",
      size: ["S", "XL"],
      color: ["gray", "blue", "red"],
      gender: "female",
      price: 250,
    },
    {
      id: "14",
      img: "hoodie6.jpg",
      name: "Casual Hoodie",
      text: "Fashion never stops. There is always the new project, the new opportunity. The important thing is to take your time and not get stressed. I just want to do what I do.",
      type: "Hoodies",
      size: ["S", "XL"],
      color: ["gray", "yellow", "blue"],
      gender: "male",
      price: 125,
    },
    {
      id: "15",
      img: "hoodie7.jpg",
      name: "Casual Hoodie",
      text: "Fashion never stops. There is always the new project, the new opportunity. The important thing is to take your time and not get stressed. I just want to do what I do.",
      type: "Hoodies",
      size: ["S", "M", "L", "XL"],
      color: ["black", "blue"],
      gender: "male",
      price: 450,
    },
    {
      id: "16",
      img: "hoodie8.jpg",
      name: "Casual Hoodie",
      text: "Fashion never stops. There is always the new project, the new opportunity. The important thing is to take your time and not get stressed. I just want to do what I do.",
      type: "Hoodies",
      size: ["S", "M", "L", "XL"],
      color: ["green", "yellow", "red"],
      gender: "female",
      price: 355,
    },

    {
      id: "17",
      img: "shoe5.jpg",
      name: "Casual Shoes",
      text: "Fashion never stops. There is always the new project, the new opportunity. The important thing is to take your time and not get stressed. I just want to do what I do.",
      type: "Shoes",
      size: ["40", "42", "44", "46"],
      color: ["black", "gray"],
      gender: "male",
      price: 200,
    },
    {
      id: "18",
      img: "shoe6.jpg",
      name: "Casual Shoes",
      text: "Fashion never stops. There is always the new project, the new opportunity. The important thing is to take your time and not get stressed. I just want to do what I do.",
      type: "Shoes",
      size: ["40", "42", "44", "46"],
      color: ["brown", "gray"],
      gender: "female",
      price: 250,
    },
    {
      id: "19",
      img: "shoe7.jpg",
      name: "Casual Shoes",
      text: "Fashion never stops. There is always the new project, the new opportunity. The important thing is to take your time and not get stressed. I just want to do what I do.",
      type: "Shoes",
      size: ["36", "38", "40", "42"],
      color: ["black", "gray", "blue"],
      gender: "female",
      price: 685,
    },
    {
      id: "20",
      img: "shoe8.jpg",
      name: "Casual Shoes",
      text: "Fashion never stops. There is always the new project, the new opportunity. The important thing is to take your time and not get stressed. I just want to do what I do.",
      type: "Shoes",
      size: ["36", "38", "40", "42"],
      color: ["black", "gray"],
      gender: "male",
      price: 255,
    },
    {
      id: "21",
      img: "shoe9.jpg",
      name: "Casual Shoes",
      text: "Fashion never stops. There is always the new project, the new opportunity. The important thing is to take your time and not get stressed. I just want to do what I do.",
      type: "Shoes",
      size: ["36", "38", "40", "42"],
      color: ["purple", "gray", "black"],
      gender: "male",
      price: 355,
    },
    {
      id: "22",
      img: "shoe10.jpg",
      name: "Casual Shoes",
      text: "Fashion never stops. There is always the new project, the new opportunity. The important thing is to take your time and not get stressed. I just want to do what I do.",
      type: "Shoes",
      size: ["36", "38", "40", "42"],
      color: ["purple", "gray", "black"],
      gender: "male",
      price: 200,
    },
    {
      id: "23",
      img: "shoe11.jpg",
      name: "Casual Shoes",
      text: "Fashion never stops. There is always the new project, the new opportunity. The important thing is to take your time and not get stressed. I just want to do what I do.",
      type: "Shoes",
      size: ["36", "38", "40", "42"],
      color: ["purple", "green", "black"],
      gender: "male",
      price: 100,
    },
    {
      id: "24",
      img: "shoe12.jpg",
      name: "Casual Shoes",
      text: "Fashion never stops. There is always the new project, the new opportunity. The important thing is to take your time and not get stressed. I just want to do what I do.",
      type: "Shoes",
      size: ["36", "38", "40", "42"],
      color: ["purple", "green", "black"],
      gender: "male",
      price: 135,
    },
    {
      id: "25",
      img: "dress1.jpg",
      name: "Casual Dress",
      text: "Fashion never stops. There is always the new project, the new opportunity. The important thing is to take your time and not get stressed. I just want to do what I do.",
      type: "Dresses",
      size: ["L", "XL"],
      color: ["purple", "blue", "gray"],
      gender: "female",
      price: 355,
    },
    {
      id: "26",
      img: "dress2.jpg",
      name: "Casual Dress",
      text: "Fashion never stops. There is always the new project, the new opportunity. The important thing is to take your time and not get stressed. I just want to do what I do.",
      type: "Dresses",
      size: ["S", "M", "XL"],
      color: ["black", "gray", "green"],
      gender: "female",
      price: 255,
    },
    {
      id: "27",
      img: "dress3.jpg",
      name: "Casual Dress",
      text: "Fashion never stops. There is always the new project, the new opportunity. The important thing is to take your time and not get stressed. I just want to do what I do.",
      type: "Dresses",
      size: ["S", "M", "XL"],
      color: ["purple", "blue", "red"],
      gender: "female",
      price: 65,
    },
    {
      id: "28",
      img: "dress4.jpg",
      name: "Casual Dress",
      text: "Fashion never stops. There is always the new project, the new opportunity. The important thing is to take your time and not get stressed. I just want to do what I do.",
      type: "Dresses",
      size: ["S", "L", "XL"],
      color: ["yellow", "blue", "orange"],
      gender: "female",
      price: 185,
    },
    {
      id: "29",
      img: "dress5.jpg",
      name: "Casual Dress",
      text: "Fashion never stops. There is always the new project, the new opportunity. The important thing is to take your time and not get stressed. I just want to do what I do.",
      type: "Dresses",
      size: ["S", "L", "XL"],
      color: ["yellow", "orange"],
      gender: "female",
      price: 555,
    },
    {
      id: "30",
      img: "dress6.jpg",
      name: "Casual Dress",
      text: "Fashion never stops. There is always the new project, the new opportunity. The important thing is to take your time and not get stressed. I just want to do what I do.",
      type: "Dresses",
      size: ["S", "M"],
      color: ["yellow", "blue", "black"],
      gender: "female",
      price: 345,
    },
    {
      id: "31",
      img: "dress7.jpg",
      name: "Casual Dress",
      text: "Fashion never stops. There is always the new project, the new opportunity. The important thing is to take your time and not get stressed. I just want to do what I do.",
      type: "Dresses",
      size: ["S", "M"],
      color: ["orange", "blue", "black"],
      gender: "female",
      price: 345,
    },
    {
      id: "32",
      img: "dress8.jpg",
      name: "Casual Dress",
      text: "Fashion never stops. There is always the new project, the new opportunity. The important thing is to take your time and not get stressed. I just want to do what I do.",
      type: "Dresses",
      size: ["M", "L"],
      color: ["brown", "blue", "red"],
      gender: "female",
      price: 685,
    },
    {
      id: "33",
      img: "jeans1.jpg",
      name: "Casual Jeans",
      text: "Experience comfort and style with our Casual Jeans, designed to flatter any figure. Crafted from premium denim, these jeans are perfect for everyday wear or special occasions. Featuring a excellent cut, the Casual Jeans offer a modern silhouette that flatters your body. The waist size is designed to accommodate most sizes, with a comfortable and adjustable fit that ensures a perfect fit every time. The leg opening is just the right size for a stylish yet practical look, while the overall length provides versatility for different heights.",
      type: "Jeans",
      size: ["S", "M", "L"],
      color: ["blue", "black"],
      gender: "male",
      price: 55,
  
    },
    {
      id: "34",
      img: "jeans2.jpg",
      name: "Casual Jeans",
      text: "Experience comfort and style with our Casual Jeans, designed to flatter any figure. Crafted from premium denim, these jeans are perfect for everyday wear or special occasions. Featuring a excellent cut, the Casual Jeans offer a modern silhouette that flatters your body. The waist size is designed to accommodate most sizes, with a comfortable and adjustable fit that ensures a perfect fit every time. The leg opening is just the right size for a stylish yet practical look, while the overall length provides versatility for different heights.",
      type: "Jeans",
      size: ["S", "M"],
      color: ["blue", "black"],
      gender: "female",
      price: 75,
    },
    {
      id: "35",
      img: "jeans3.jpg",
      name: "Casual Jeans",
      text: "Experience comfort and style with our Casual Jeans, designed to flatter any figure. Crafted from premium denim, these jeans are perfect for everyday wear or special occasions. Featuring a excellent cut, the Casual Jeans offer a modern silhouette that flatters your body. The waist size is designed to accommodate most sizes, with a comfortable and adjustable fit that ensures a perfect fit every time. The leg opening is just the right size for a stylish yet practical look, while the overall length provides versatility for different heights.",
      type: "Jeans",
      size: ["M", "L", "XL"],
      color: ["blue", "black"],
      gender: "male",
      price: 95,
    },
    {
      id: "36",
      img: "jeans4.jpg",
      name: "Casual Jeans",
      text: "Experience comfort and style with our Casual Jeans, designed to flatter any figure. Crafted from premium denim, these jeans are perfect for everyday wear or special occasions. Featuring a excellent cut, the Casual Jeans offer a modern silhouette that flatters your body. The waist size is designed to accommodate most sizes, with a comfortable and adjustable fit that ensures a perfect fit every time. The leg opening is just the right size for a stylish yet practical look, while the overall length provides versatility for different heights.",
      type: "Jeans",
      size: ["M", "L", "XL"],
      color: ["blue", "black"],
      gender: "female",
      price: 100,
    },
    {
      id: "37",
      img: "jeans5.jpg",
      name: "Casual Jeans",
      text: "Experience comfort and style with our Casual Jeans, designed to flatter any figure. Crafted from premium denim, these jeans are perfect for everyday wear or special occasions. Featuring a excellent cut, the Casual Jeans offer a modern silhouette that flatters your body. The waist size is designed to accommodate most sizes, with a comfortable and adjustable fit that ensures a perfect fit every time. The leg opening is just the right size for a stylish yet practical look, while the overall length provides versatility for different heights.",
      type: "Jeans",
      size: ["M", "L", "XL"],
      color: ["blue", "black"],
      gender: "female",
      price: 200,
    },
    {
      id: "37",
      img: "jeans6.jpg",
      name: "Casual Jeans",
      text: "Experience comfort and style with our Casual Jeans, designed to flatter any figure. Crafted from premium denim, these jeans are perfect for everyday wear or special occasions. Featuring a excellent cut, the Casual Jeans offer a modern silhouette that flatters your body. The waist size is designed to accommodate most sizes, with a comfortable and adjustable fit that ensures a perfect fit every time. The leg opening is just the right size for a stylish yet practical look, while the overall length provides versatility for different heights.",
      type: "Jeans",
      size: ["S", "L", "XL"],
      color: ["blue", "black"],
      gender: "female",
      price: 200,
    },
    {
      id: "38",
      img: "jeans7.jpg",
      name: "Casual Jeans",
      text: "Experience comfort and style with our Casual Jeans, designed to flatter any figure. Crafted from premium denim, these jeans are perfect for everyday wear or special occasions. Featuring a excellent cut, the Casual Jeans offer a modern silhouette that flatters your body. The waist size is designed to accommodate most sizes, with a comfortable and adjustable fit that ensures a perfect fit every time. The leg opening is just the right size for a stylish yet practical look, while the overall length provides versatility for different heights.",
      type: "Jeans",
      size: ["M", "L", "XL"],
      color: ["blue", "black"],
      gender: "male",
      price: 180,
    },
    {
      id: "39",
      img: "jeans8.jpg",
      name: "Casual Jeans",
      text: "Experience comfort and style with our Casual Jeans, designed to flatter any figure. Crafted from premium denim, these jeans are perfect for everyday wear or special occasions. Featuring a excellent cut, the Casual Jeans offer a modern silhouette that flatters your body. The waist size is designed to accommodate most sizes, with a comfortable and adjustable fit that ensures a perfect fit every time. The leg opening is just the right size for a stylish yet practical look, while the overall length provides versatility for different heights.",
      type: "Jeans",
      size: ["M", "L", "XL"],
      color: ["blue", "black"],
      gender: "male",
      price: 160,
    },
    {
      id: "40",
      img: "jacket1.jpg",
      name: "Casual Jacket",
      text: "Fashion never stops. There is always the new project, the new opportunity. The important thing is to take your time and not get stressed. I just want to do what I do.",
      type: "Jackets",
      size: ["M", "L", "XL"],
      color: ["black", "blue"],
      gender: "male",
      price: 400,
    },
    {
      id: "41",
      img: "jacket2.jpg",
      name: "Casual Jacket",
      text: "Fashion never stops. There is always the new project, the new opportunity. The important thing is to take your time and not get stressed. I just want to do what I do.",
      type: "Jackets",
      size: ["S", "L", "XL"],
      color: ["gray", "brown"],
      gender: "male",
      price: 255,
    },
    {
      id: "42",
      img: "jacket3.jpg",
      name: "Casual Jacket",
      text: "Fashion never stops. There is always the new project, the new opportunity. The important thing is to take your time and not get stressed. I just want to do what I do.",
      type: "Jackets",
      size: ["S", "M"],
      color: ["gray", "brown"],
      gender: "male",
      price: 300,
    },
    {
      id: "43",
      img: "jacket4.jpg",
      name: "Casual Jacket",
      text: "Fashion never stops. There is always the new project, the new opportunity. The important thing is to take your time and not get stressed. I just want to do what I do.",
      type: "Jackets",
      size: ["S", "M", "L"],
      color: ["gray", "brown"],
      gender: "male",
      price: 185,
    },
    {
      id: "44",
      img: "jacket5.jpg",
      name: "Casual Jacket",
      text: "Fashion never stops. There is always the new project, the new opportunity. The important thing is to take your time and not get stressed. I just want to do what I do.",
      type: "Jackets",
      size: ["S", "M", "L"],
      color: ["gray", "brown"],
      gender: "female",
      price: 185,
    },
    {
      id: "45",
      img: "jacket6.jpg",
      name: "Casual Jacket",
      text: "Fashion never stops. There is always the new project, the new opportunity. The important thing is to take your time and not get stressed. I just want to do what I do.",
      type: "Jackets",
      size: ["S", "M", "XL"],
      color: ["gray", "brown", "black"],
      gender: "male",
      price: 285,
    },
    {
      id: "46",
      img: "jacket7.jpg",
      name: "Casual Jacket",
      text: "Fashion never stops. There is always the new project, the new opportunity. The important thing is to take your time and not get stressed. I just want to do what I do.",
      type: "Jackets",
      size: ["S", "M", "XL"],
      color: ["brown", "black"],
      gender: "female",
      price: 425,
    },
    {
      id: "47",
      img: "jacket8.jpg",
      name: "Casual Jacket",
      text: "Fashion never stops. There is always the new project, the new opportunity. The important thing is to take your time and not get stressed. I just want to do what I do.",
      type: "Jackets",
      size: ["M", "L", "XL"],
      color: ["yellow", "orange", "blue"],
      gender: "female",
      price: 335,
    },
    {
      id: "48",
      img: "bag1.jpg",
      name: "Casual Bag",
      text: "Fashion never stops. There is always the new project, the new opportunity. The important thing is to take your time and not get stressed. I just want to do what I do.",
      type: "Bags",
      color: ["black", "blue", "red"],
      gender: "female",
      price: 500,
    },
    {
      id: "49",
      img: "bag2.jpg",
      name: "Casual Bag",
      text: "Fashion never stops. There is always the new project, the new opportunity. The important thing is to take your time and not get stressed. I just want to do what I do.",
      type: "Bags",
      color: ["green", "red", "blue"],
      gender: "male",
      price: 85,
    },
    {
      id: "50",
      img: "bag3.jpg",
      name: "Casual Bag",
      text: "Fashion never stops. There is always the new project, the new opportunity. The important thing is to take your time and not get stressed. I just want to do what I do.",
      type: "Bags",
      color: ["brown", "blue", "orange"],
      gender: "female",
      price: 200,
    },
    {
      id: "51",
      img: "bag4.jpg",
      name: "Casual Bag",
      text: "Fashion never stops. There is always the new project, the new opportunity. The important thing is to take your time and not get stressed. I just want to do what I do.",
      type: "Bags",
      color: ["brown", "blue", "orange"],
      gender: "female",
      price: 25,
    },
    {
      id: "52",
      img: "bag5.jpg",
      name: "Casual Bag",
      text: "Fashion never stops. There is always the new project, the new opportunity. The important thing is to take your time and not get stressed. I just want to do what I do.",
      type: "Bags",
      color: ["yellow", "blue", "black"],
      gender: "female",
      price: 40,
    },
    {
      id: "53",
      img: "bag6.jpg",
      name: "Casual Bag",
      text: "Fashion never stops. There is always the new project, the new opportunity. The important thing is to take your time and not get stressed. I just want to do what I do.",
      type: "Bags",
      color: ["blue", "black", "orange"],
      gender: "female",
      price: 400,
    },
    {
      id: "54",
      img: "bag7.jpg",
      name: "Casual Bag",
      text: "Fashion never stops. There is always the new project, the new opportunity. The important thing is to take your time and not get stressed. I just want to do what I do.",
      type: "Bags",
      color: ["blue", "black", "orange"],
      gender: "female",
      price: 355,
    },
    {
      id: "55",
      img: "bag8.jpg",
      name: "Casual Bag",
      text: "Fashion never stops. There is always the new project, the new opportunity. The important thing is to take your time and not get stressed. I just want to do what I do.",
      type: "Bags",
      color: ["blue", "green", "red"],
      gender: "female",
      price: 100,
    },
    {
      id: "56",
      img: "suit1.jpg",
      name: "Casual Suit",
      text: "Fashion never stops. There is always the new project, the new opportunity. The important thing is to take your time and not get stressed. I just want to do what I do.",
      type: "Suits",
      size: ["S", "M", "L"],
      color: ["black", "gray", "orange"],
      gender: "male",
      price: 300,
    },
    {
      id: "57",
      img: "suit2.jpg",
      name: "Casual Suit",
      text: "Fashion never stops. There is always the new project, the new opportunity. The important thing is to take your time and not get stressed. I just want to do what I do.",
      type: "Suits",
      size: ["S", "M", "L"],
      color: ["purple", "orange", "gray"],
      gender: "male",
      price: 400,
    },
    {
      id: "58",
      img: "suit3.jpg",
      name: "Casual Suit",
      text: "Fashion never stops. There is always the new project, the new opportunity. The important thing is to take your time and not get stressed. I just want to do what I do.",
      type: "Suits",
      size: ["M", "L", "XL"],
      color: ["purple", "orange", "gray"],
      gender: "male",
      price: 200,
    },
    {
      id: "59",
      img: "suit4.jpg",
      name: "Casual Suit",
      text: "Fashion never stops. There is always the new project, the new opportunity. The important thing is to take your time and not get stressed. I just want to do what I do.",
      type: "Suits",
      size: ["L", "XL"],
      color: ["brown", "orange", "black"],
      gender: "male",
      price: 600,
    },
    {
      id: "60",
      img: "suit5.jpg",
      name: "Casual Suit",
      text: "Fashion never stops. There is always the new project, the new opportunity. The important thing is to take your time and not get stressed. I just want to do what I do.",
      type: "Suits",
      size: ["L", "XL"],
      color: ["black", "blue", "red"],
      gender: "male",
      price: 750,
    },
    {
      id: "61",
      img: "suit6.jpg",
      name: "Casual Suit",
      text: "Fashion never stops. There is always the new project, the new opportunity. The important thing is to take your time and not get stressed. I just want to do what I do.",
      type: "Suits",
      size: ["S", "M"],
      color: ["brown", "orange", "black"],
      gender: "female",
      price: 385,
    },
    {
      id: "62",
      img: "suit7.jpg",
      name: "Casual Suit",
      text: "Fashion never stops. There is always the new project, the new opportunity. The important thing is to take your time and not get stressed. I just want to do what I do.",
      type: "Suits",
      size: ["L", "XL"],
      color: ["red", "blue", "black"],
      gender: "male",
      price: 700,
    },
    {
      id: "63",
      img: "suit8.jpg",
      name: "Casual Suit",
      text: "Fashion never stops. There is always the new project, the new opportunity. The important thing is to take your time and not get stressed. I just want to do what I do.",
      type: "Suits",
      size: ["S", "M", "XL"],
      color: ["blue", "green", "brown"],
      gender: "male",
      price: 550,
    },
    {
      id: "64",
      img: "shoe1.jpg",
      name: "Casual Shoes",
      text: "Fashion never stops. There is always the new project, the new opportunity. The important thing is to take your time and not get stressed. I just want to do what I do.",
      type: "Shoes",
      size: ["40", "42", "44", "46"],
      color: ["black", "gray"],
      gender: "male",
      price: 200,
    },
    {
      id: "65",
      img: "shoe2.jpg",
      name: "Casual Shoes",
      text: "Fashion never stops. There is always the new project, the new opportunity. The important thing is to take your time and not get stressed. I just want to do what I do.",
      type: "Shoes",
      size: ["40", "42", "44", "46"],
      color: ["brown", "gray"],
      gender: "female",
      price: 250,
    },
    {
      id: "66",
      img: "shoe3.jpg",
      name: "Casual Shoes",
      text: "Fashion never stops. There is always the new project, the new opportunity. The important thing is to take your time and not get stressed. I just want to do what I do.",
      type: "Shoes",
      size: ["36", "38", "40", "42"],
      color: ["black", "gray", "blue"],
      gender: "female",
      price: 685,
    },
    {
      id: "67",
      img: "shoe4.jpg",
      name: "Casual Shoes",
      text: "Fashion never stops. There is always the new project, the new opportunity. The important thing is to take your time and not get stressed. I just want to do what I do.",
      type: "Shoes",
      size: ["36", "38", "40", "42"],
      color: ["black", "gray"],
      gender: "male",
      price: 255,
    },
   
  ];
  testData.map(async (product) => {
    const response = await axios.post(`${server}/product`, product);
    console.log(response.data);
  });
};
createProducts();
